Api gateway config
hmcts/ccpay-payment-api-gateway pull request #25
Opened 2019-11-07 11:36 UTC by YasharRahvar

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PAY-2550
https://tools.hmcts.net/jira/browse/PAY-2449

### Change description ###
 Moving all api configuration for fee & pay team into https://github.com/hmcts/ccpay-payment-api-gateway
Reconfiguring api gateway configuration using native terraform resources 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2019-11-07 11:50 UTC, timja requested changes
Lots of small fixes needed, added suggestions you can apply,

2019-11-07 11:50 UTC, timja commented on bulk-scanning.tf
> +  api_mgmt_name         = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name         = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on bulk-scanning.tf
> +  api_mgmt_rg           = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg           = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on bulk-scanning.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on bulk-scanning.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg   = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on bulk-scanning.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg   = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on payments.tf
> +  api_mgmt_rg           = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg           = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on payments.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg   = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on payments.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg   = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on telephony.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg   = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on telephony.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg   = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on telephony.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
```suggestion
  api_mgmt_rg   = "core-infra-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on bulk-scanning.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on payments.tf
> +  api_mgmt_name         = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name         = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on payments.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on payments.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on telephony.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on telephony.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on telephony.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
```suggestion
  api_mgmt_name = "core-api-mgmt-${var.env}"
```

2019-11-07 11:50 UTC, timja commented on main.tf
> +  version = "1.22.1"
the current version doesn't have support for api management, it needs a newer one
```suggestion
    version = "1.36.1"
```

2019-11-07 11:50 UTC, timja commented on main.tf
> +  key_vault_id = data.azurerm_key_vault.payment_key_vault.id
the terraform version on jenkins doesn't support this (needs upgrading)
```suggestion
  key_vault_id = "${data.azurerm_key_vault.payment_key_vault.id}"
```

2019-11-07 11:50 UTC, timja commented on main.tf
> +  key_vault_id = data.azurerm_key_vault.payment_key_vault.id
```suggestion
  key_vault_id = "${data.azurerm_key_vault.payment_key_vault.id}"
```

2019-11-07 11:50 UTC, timja commented on saat.tfvars
> +# API Gateway Thumbprints
this environment doesn't exist anymore, delete the file

2019-11-07 11:50 UTC, timja commented on variables.tf
> +  default = []
```suggestion
```

2019-11-07 11:50 UTC, timja commented on variables.tf
> +  # TODO: remove default and provide environment-specific values
```suggestion
```

2019-11-07 11:50 UTC, timja commented on variables.tf
> +  # TODO: remove default and provide environment-specific values
```suggestion
```

2019-11-07 11:50 UTC, timja commented on variables.tf
>    default = []
```suggestion
```

2019-11-07 11:50 UTC, timja commented on variables.tf
>    # TODO: remove default and provide environment-specific values
```suggestion
```

2019-11-07 11:50 UTC, timja requested changes
Lots of small fixes needed, added suggestions you can apply,

2019-11-07 12:17 UTC, YasharRahvar commented on bulk-scanning.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
Updated.

2019-11-07 12:17 UTC, YasharRahvar commented on bulk-scanning.tf
> +  api_mgmt_rg   = "core-infra-demodata-rg"
Updated.

2019-11-07 12:17 UTC, YasharRahvar commented on bulk-scanning.tf
> +  api_mgmt_name = "core-api-mgmt-demodata"
Updated.

2019-11-07 12:17 UTC, YasharRahvar commented on bulk-scanning.tf
> +  api_mgmt_rg           = "core-infra-demodata-rg"
Updated.

2019-11-07 12:17 UTC, YasharRahvar commented on bulk-scanning.tf
> +  api_mgmt_name         = "core-api-mgmt-demodata"
Updated.

2019-11-07 13:03 UTC, timja approved these changes

2021-04-08 16:31 UTC, vijayrajagopalan-hmcts reviewed
Is this PR still relevant?

2026-03-22 19:13 UTC, closed without merging